package channel

import (
	"bufio"
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Records in the shape Claude Code 2.1.280 writes them (observed 2026-09-23): a
// channel event is a user record with isMeta and the <channel> tag as content.
func rec(typ, ts, extra string) string {
	return `{"type":"` + typ + `","timestamp":"2026-09-23T` + ts + `.000Z"` + extra + "}\n"
}

const (
	human     = `,"message":{"role":"user","content":"OK とだけ返して"}`
	toolRes   = `,"message":{"role":"user","content":[{"type":"tool_result","content":"x"}]}`
	beat      = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"ccx\" kind=\"heartbeat\">\nheartbeat\n</channel>"}`
	otherChan = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"akapen\" file=\"a.md\">\nhi\n</channel>"}`
	metaNote  = `,"isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands."}`
	reply     =`,"message":{"role":"assistant","content":[{"type":"text","text":"."}]}`
)

func at(s string) time.Time { t, _ := time.Parse(time.RFC3339, "2026-09-23T"+s+"Z"); return t }

func TestScanTranscript(t *testing.T) {
	tr := rec("user", "10:00:00", human) +
		rec("assistant", "10:00:05", reply) +
		rec("user", "10:00:06", toolRes) +
		rec("assistant", "10:00:10", reply) +
		rec("attachment", "10:00:11", "") +
		rec("user", "10:50:10", beat) +
		rec("user", "10:50:11", metaNote) + // a meta record that is not a channel stays in the turn
		rec("assistant", "10:50:12", reply) +
		rec("user", "10:50:13", toolRes) + // a tool result inside a heartbeat turn stays in it
		rec("assistant", "10:50:14", reply) +
		"not json\n"

	s := ScanTranscript(strings.NewReader(tr))
	if !s.LastAssistant.Equal(at("10:50:14")) {
		t.Errorf("LastAssistant = %v, want the heartbeat's reply", s.LastAssistant)
	}
	if !s.LastReal.Equal(at("10:00:10")) {
		t.Errorf("LastReal = %v, want the last record before the heartbeat", s.LastReal)
	}
	if !s.LastBeat.Equal(at("10:50:10")) {
		t.Errorf("LastBeat = %v", s.LastBeat)
	}

	// A person speaking again ends the heartbeat turn; so does another channel.
	for _, next := range []string{human, otherChan} {
		s = ScanTranscript(strings.NewReader(tr + rec("user", "11:00:00", next) + rec("assistant", "11:00:02", reply)))
		if !s.LastReal.Equal(at("11:00:02")) {
			t.Errorf("after %s: LastReal = %v, want 11:00:02", next[:30], s.LastReal)
		}
	}
}

// fixture writes a session transcript under a temp ClaudeHome and returns a
// Heartbeat whose clock and push are recorded.
func fixture(t *testing.T, transcript string, now time.Time) (*Heartbeat, *int, func(string)) {
	t.Helper()
	home := t.TempDir()
	dir := filepath.Join(home, "projects", "-some-cwd")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(dir, "sid.jsonl")
	pushes := 0
	h := &Heartbeat{
		SessionID: "sid", ClaudeHome: home, Interval: 50 * time.Minute, MaxIdle: 12 * time.Hour,
		Push: func() error { pushes++; return nil },
		Log:  t.Logf,
		Now:  func() time.Time { return now },
	}
	write := func(s string) {
		if err := os.WriteFile(file, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
		h.mtime = time.Time{} // same-second rewrites keep the mtime; force a rescan
	}
	write(transcript)
	return h, &pushes, write
}

func TestStepPushesOnlyWhenDue(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)

	h, pushes, _ := fixture(t, tr, at("10:30:05"))
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != 20*time.Minute {
		t.Errorf("before due: pushes=%d wait=%v, want 0 and the time left", *pushes, wait)
	}

	h.Now = func() time.Time { return at("10:50:05") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("at due: pushes=%d, want 1", *pushes)
	}
}

func TestStepNeverStacksAnUndeliveredBeat(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, write := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)

	// Hours later, still not in the transcript (/clear moved the session on).
	h.Now = func() time.Time { return at("13:00:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("undelivered: pushes=%d, want still 1", *pushes)
	}

	// Once it lands and is answered, the next one is due an interval later.
	write(tr + rec("user", "10:50:06", beat) + rec("assistant", "10:50:08", reply))
	h.Now = func() time.Time { return at("11:40:08") }
	h.step(&sent)
	if *pushes != 2 {
		t.Fatalf("after delivery: pushes=%d, want 2", *pushes)
	}
}

func TestStepStopsWhenLeftAlone(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "21:50:00", beat) + rec("assistant", "21:50:02", reply)
	// The last heartbeat was answered; 12h after the person last used it, stop.
	h, pushes, _ := fixture(t, tr, at("22:40:02"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("past MaxIdle: pushes=%d, want 0", *pushes)
	}
	h.MaxIdle = 24 * time.Hour
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("within MaxIdle: pushes=%d, want 1", *pushes)
	}
}

func TestStepSkipsArchived(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:05"))
	dir := filepath.Join(h.ClaudeHome, "sessions", "sid")
	_ = os.MkdirAll(dir, 0o755)
	_ = os.WriteFile(filepath.Join(dir, "archived"), nil, 0o644)
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("archived: pushes=%d, want 0", *pushes)
	}
}

func TestStepWaitsForATranscript(t *testing.T) {
	h, pushes, _ := fixture(t, "", at("10:50:05"))
	h.SessionID = "not-started"
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != poll {
		t.Errorf("no transcript: pushes=%d wait=%v", *pushes, wait)
	}
}

func TestServe(t *testing.T) {
	in := strings.Join([]string{
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}`,
		`{"jsonrpc":"2.0","method":"notifications/initialized"}`,
		`{"jsonrpc":"2.0","id":2,"method":"ping"}`,
		`{"jsonrpc":"2.0","id":3,"method":"tools/list"}`,
	}, "\n") + "\n"
	var out bytes.Buffer
	s := NewServer("ccx", "0", &out)
	if err := s.Serve(strings.NewReader(in)); err != nil {
		t.Fatal(err)
	}
	if err := s.Push("heartbeat", map[string]string{"kind": "heartbeat"}); err != nil {
		t.Fatal(err)
	}

	var msgs []map[string]any
	sc := bufio.NewScanner(&out)
	for sc.Scan() {
		var m map[string]any
		if err := json.Unmarshal(sc.Bytes(), &m); err != nil {
			t.Fatalf("not JSON: %s", sc.Text())
		}
		msgs = append(msgs, m)
	}
	if len(msgs) != 4 {
		t.Fatalf("got %d messages, want 4 (no answer to a notification): %v", len(msgs), msgs)
	}
	init := msgs[0]["result"].(map[string]any)
	if init["protocolVersion"] != "2025-06-18" {
		t.Errorf("protocolVersion = %v, want the client's echoed", init["protocolVersion"])
	}
	exp := init["capabilities"].(map[string]any)["experimental"].(map[string]any)
	if _, ok := exp["claude/channel"]; !ok {
		t.Error("claude/channel capability missing: the session would never register the channel")
	}
	if msgs[1]["result"] == nil {
		t.Error("ping unanswered")
	}
	if msgs[2]["error"] == nil {
		t.Error("unknown method answered as if it existed")
	}
	if msgs[3]["method"] != "notifications/claude/channel" {
		t.Errorf("push = %v", msgs[3])
	}
}

// The instructions reach the transcript as an attachment; if they carried the
// marker, a scan would mistake them for a heartbeat.
func TestInstructionsDoNotCarryTheMarker(t *testing.T) {
	b, _ := json.Marshal(Instructions)
	if bytes.Contains(b, []byte(Marker)) {
		t.Error("Instructions contain Marker")
	}
}
