package heartbeat

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Records in the shape Claude Code 2.1.280 writes them (observed 2026-09-23): a
// channel event is a user record with isMeta and the <channel> tag as content.
func rec(typ, ts, extra string) string {
	return `{"type":"` + typ + `","timestamp":"2026-09-23T` + ts + `.000Z"` + extra + "}\n"
}

const (
	human     = `,"message":{"role":"user","content":"OK とだけ返して"}`
	toolRes   = `,"message":{"role":"user","content":[{"type":"tool_result","content":"x"}]}`
	beat      = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"ccx\" kind=\"heartbeat\">\nheartbeat\n</channel>"}`
	otherChan = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"akapen\" file=\"a.md\">\nhi\n</channel>"}`
	metaNote  = `,"isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands."}`
	reply     = `,"message":{"role":"assistant","content":[{"type":"text","text":"."}]}`
)

func at(s string) time.Time { t, _ := time.Parse(time.RFC3339, "2026-09-23T"+s+"Z"); return t }

func mustScan(t *testing.T, transcript string) Scan {
	t.Helper()
	s, err := ScanTranscript(strings.NewReader(transcript))
	if err != nil {
		t.Fatal(err)
	}
	return s
}

// A line longer than the scanner allows ends the scan early. That must be an
// error, or the session would be dated from whatever came before it.
func TestScanTranscriptReportsATruncatedRead(t *testing.T) {
	long := rec("user", "10:00:00", human) + `{"type":"user","x":"` + strings.Repeat("a", 65*1024*1024) + "\"}\n"
	if _, err := ScanTranscript(strings.NewReader(long)); err == nil {
		t.Error("no error for a line past the buffer")
	}
}

func TestStepSkipsAnExpiredCache(t *testing.T) {
	// Resumed or woken 3h after the last request: the cache is gone, and a
	// heartbeat would only pay the rewrite early.
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("13:00:05"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("expired: pushes=%d, want 0", *pushes)
	}
	h.Now = func() time.Time { return at("10:59:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("due and still warm: pushes=%d, want 1", *pushes)
	}
}

func TestScanTranscript(t *testing.T) {
	tr := rec("user", "10:00:00", human) +
		rec("assistant", "10:00:05", reply) +
		rec("user", "10:00:06", toolRes) +
		rec("assistant", "10:00:10", reply) +
		rec("attachment", "10:00:11", "") +
		rec("user", "10:50:10", beat) +
		rec("user", "10:50:11", metaNote) + // a meta record that is not a channel stays in the turn
		rec("assistant", "10:50:12", reply) +
		rec("user", "10:50:13", toolRes) + // a tool result inside a heartbeat turn stays in it
		rec("assistant", "10:50:14", reply) +
		"not json\n"

	s := mustScan(t, tr)
	if !s.LastAssistant.Equal(at("10:50:14")) {
		t.Errorf("LastAssistant = %v, want the heartbeat's reply", s.LastAssistant)
	}
	if !s.LastReal.Equal(at("10:00:10")) {
		t.Errorf("LastReal = %v, want the last record before the heartbeat", s.LastReal)
	}
	if !s.LastBeat.Equal(at("10:50:10")) {
		t.Errorf("LastBeat = %v", s.LastBeat)
	}

	// Quoting the attribute is not a heartbeat: a person asking about it, a tool
	// reading this code, an attachment carrying the instructions.
	for _, quote := range []string{
		`,"message":{"role":"user","content":"what does kind=\"heartbeat\" mean?"}`,
		`,"message":{"role":"user","content":[{"type":"tool_result","content":"<channel source=\"ccx\" kind=\"heartbeat\">"}]}`,
		`,"message":{"role":"user","content":"<channel source=\"ccx\" kind=\"heartbeat\"> pasted by a person"}`,
		`,"isMeta":true,"message":{"role":"user","content":"<channel source=\"akapen\" file=\"a.md\">\nwhy kind=\"heartbeat\"?\n</channel>"}`,
	} {
		s = mustScan(t, rec("user", "10:00:00", human)+rec("user", "10:10:00", quote)+rec("assistant", "10:10:05", reply))
		if !s.LastBeat.IsZero() || !s.LastReal.Equal(at("10:10:05")) {
			t.Errorf("%s: LastBeat=%v LastReal=%v, want no beat and real use", quote[:40], s.LastBeat, s.LastReal)
		}
	}
	s = mustScan(t, rec("attachment", "10:00:00", `,"attachment":{"content":"<channel source=\"ccx\" kind=\"heartbeat\">"}`))
	if !s.LastBeat.IsZero() {
		t.Errorf("attachment read as a beat")
	}

	// A person speaking again ends the heartbeat turn; so does another channel.
	for _, next := range []string{human, otherChan} {
		s = mustScan(t, tr+rec("user", "11:00:00", next)+rec("assistant", "11:00:02", reply))
		if !s.LastReal.Equal(at("11:00:02")) {
			t.Errorf("after %s: LastReal = %v, want 11:00:02", next[:30], s.LastReal)
		}
	}
}

// fixture writes a session transcript under a temp ClaudeHome and returns a
// Heartbeat whose clock and push are recorded.
func fixture(t *testing.T, transcript string, now time.Time) (*Heartbeat, *int, func(string)) {
	t.Helper()
	home := t.TempDir()
	dir := filepath.Join(home, "projects", "-some-cwd")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(dir, "sid.jsonl")
	pushes := 0
	h := &Heartbeat{
		SessionID: "sid", ClaudeHome: home, Interval: 50 * time.Minute, MaxIdle: 12 * time.Hour, Default: true,
		Push: func() error { pushes++; return nil },
		Log:  t.Logf,
		Now:  func() time.Time { return now },
	}
	write := func(s string) {
		if err := os.WriteFile(file, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
		h.mtime = time.Time{} // same-second rewrites keep the mtime; force a rescan
	}
	write(transcript)
	return h, &pushes, write
}

func TestStepPushesOnlyWhenDue(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)

	h, pushes, _ := fixture(t, tr, at("10:30:05"))
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != 20*time.Minute {
		t.Errorf("before due: pushes=%d wait=%v, want 0 and the time left", *pushes, wait)
	}

	h.Now = func() time.Time { return at("10:50:05") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("at due: pushes=%d, want 1", *pushes)
	}
}

func TestStepNeverStacksAnUndeliveredBeat(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, write := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)

	// Hours later, still not in the transcript (/clear moved the session on).
	h.Now = func() time.Time { return at("13:00:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("undelivered: pushes=%d, want still 1", *pushes)
	}

	// Once it lands and is answered, the next one is due an interval after the
	// reply, not after the person's last turn.
	write(tr + rec("user", "10:50:06", beat) + rec("assistant", "10:50:08", reply))
	h.Now = func() time.Time { return at("11:30:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("before the next due: pushes=%d, want still 1", *pushes)
	}
	h.Now = func() time.Time { return at("11:40:08") }
	h.step(&sent)
	if *pushes != 2 {
		t.Fatalf("after delivery: pushes=%d, want 2", *pushes)
	}
}

// A heartbeat whose answer took five minutes: the cache was read at the start of
// that last request, so the next one is due from it, not from the heartbeat.
func TestStepCountsFromTheLastRequest(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "10:50:06", beat) + rec("assistant", "10:55:00", reply)
	h, pushes, _ := fixture(t, tr, at("11:42:00"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("before last request + interval: pushes=%d, want 0", *pushes)
	}
}

func TestStepRecoversFromALostBeat(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, write := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)

	// The push was lost (interrupted, dropped), but the person came back and used
	// the session. That session is alive; it must be kept warm again.
	tr += rec("user", "11:00:00", human) + rec("assistant", "11:00:05", reply)
	write(tr)
	h.Now = func() time.Time { return at("11:50:05") }
	h.step(&sent)
	if *pushes != 2 {
		t.Fatalf("after real use: pushes=%d, want 2", *pushes)
	}
}

func TestStepDoesNotRepeatAnUnansweredBeat(t *testing.T) {
	// Delivered, but the answer never came (the request failed).
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) + rec("user", "10:50:06", beat)
	h, pushes, _ := fixture(t, tr, at("10:51:06"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Fatalf("a minute after an unanswered beat: pushes=%d, want 0", *pushes)
	}
	h.Now = func() time.Time { return at("11:40:06") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("an interval after it: pushes=%d, want 1", *pushes)
	}
}

func TestStepStopsWhenLeftAlone(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "21:50:00", beat) + rec("assistant", "21:50:02", reply)
	// The last heartbeat was answered; 12h after the person last used it, stop.
	h, pushes, _ := fixture(t, tr, at("22:40:02"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("past MaxIdle: pushes=%d, want 0", *pushes)
	}
	h.MaxIdle = 24 * time.Hour
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("within MaxIdle: pushes=%d, want 1", *pushes)
	}

	// off (0) is no cap, not "always past it".
	h2, pushes2, _ := fixture(t, tr, at("22:40:02"))
	h2.MaxIdle = 0
	var sent2 time.Time
	h2.step(&sent2)
	if *pushes2 != 1 {
		t.Errorf("MaxIdle off: pushes=%d, want 1", *pushes2)
	}
}

// A session's own on / off wins over the machine's default, both ways, and a
// change takes effect on the next step without a restart.
func TestStepFollowsTheSessionsDeclaration(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	for _, c := range []struct {
		def  bool
		file string
		want int
	}{
		{true, "", 1}, {false, "", 0},
		{true, "off\n", 0}, {false, "on\n", 1},
		{false, "garbage", 0}, {true, "garbage", 1},
	} {
		h, pushes, _ := fixture(t, tr, at("10:50:05"))
		h.Default = c.def
		if c.file != "" {
			dir := filepath.Join(h.ClaudeHome, "sessions", "sid")
			_ = os.MkdirAll(dir, 0o755)
			_ = os.WriteFile(filepath.Join(dir, "heartbeat"), []byte(c.file), 0o644)
		}
		var sent time.Time
		if wait := h.step(&sent); *pushes != c.want {
			t.Errorf("default=%v file=%q: pushes=%d, want %d", c.def, c.file, *pushes, c.want)
		} else if c.want == 0 && wait != poll {
			t.Errorf("default=%v file=%q: wait=%v, want poll so turning it on is seen soon", c.def, c.file, wait)
		}
	}
}

func TestStepSkipsArchived(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:05"))
	dir := filepath.Join(h.ClaudeHome, "sessions", "sid")
	_ = os.MkdirAll(dir, 0o755)
	_ = os.WriteFile(filepath.Join(dir, "archived"), nil, 0o644)
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("archived: pushes=%d, want 0", *pushes)
	}
}

func TestStepWaitsForATranscript(t *testing.T) {
	h, pushes, _ := fixture(t, "", at("10:50:05"))
	h.SessionID = "not-started"
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != poll {
		t.Errorf("no transcript: pushes=%d wait=%v", *pushes, wait)
	}
}
