package heartbeat

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Records in the shape Claude Code 2.1.280 writes them (observed 2026-09-23): a
// channel event is a user record with isMeta and the <channel> tag as content.
//
// Each record's parentUuid is the record built just before it, the chain Claude
// Code writes (records are built in transcript order in these tests).
func rec(typ, ts, extra string) string {
	recN++
	id := fmt.Sprintf("r%d", recN)
	parent := lastRec
	lastRec = id
	return `{"type":"` + typ + `","uuid":"` + id + `","parentUuid":"` + parent + `","timestamp":"2026-09-23T` + ts + `.000Z"` + extra + "}\n"
}

var (
	recN    int
	lastRec string
)

const (
	human       = `,"message":{"role":"user","content":"OK とだけ返して"}`
	toolRes     = `,"message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1","content":"x"}]}`
	beat        = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"ccx\" kind=\"heartbeat\">\nheartbeat\n</channel>"}`
	otherChan   = `,"isMeta":true,"message":{"role":"user","content":"<channel source=\"akapen\" file=\"a.md\">\nhi\n</channel>"}`
	metaNote    = `,"isMeta":true,"message":{"role":"user","content":"Caveat: the messages below were generated by the user while running local commands."}`
	reply       = `,"message":{"role":"assistant","content":[{"type":"text","text":"."}]}`
	toolUse     = `,"message":{"role":"assistant","content":[{"type":"tool_use","id":"t1","name":"Bash","input":{}}]}`
	toolUse2    = `,"message":{"role":"assistant","content":[{"type":"tool_use","id":"t2","name":"Bash","input":{}}]}`
	toolRes2    = `,"message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t2","content":"x"}]}`
	toolResX    = `,"message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t9","content":"x"}]}`
	interrupted = `,"message":{"role":"user","content":[{"type":"text","text":"[Request interrupted by user]"}]}`
	crossMsg    = `,"isMeta":true,"message":{"role":"user","content":"<cross-session-message from=\"x\">\nhi\n</cross-session-message>"}`
	apiError    = `,"isApiErrorMessage":true,"message":{"role":"assistant","content":[{"type":"text","text":"Prompt is too long"}]}`
)

func at(s string) time.Time { t, _ := time.Parse(time.RFC3339, "2026-09-23T"+s+"Z"); return t }

func mustScan(t *testing.T, transcript string) Scan {
	t.Helper()
	s, err := ScanTranscript(strings.NewReader(transcript))
	if err != nil {
		t.Fatal(err)
	}
	return s
}

// A line longer than the scanner allows ends the scan early. That must be an
// error, or the session would be dated from whatever came before it.
func TestScanTranscriptReportsATruncatedRead(t *testing.T) {
	long := rec("user", "10:00:00", human) + `{"type":"user","x":"` + strings.Repeat("a", 65*1024*1024) + "\"}\n"
	if _, err := ScanTranscript(strings.NewReader(long)); err == nil {
		t.Error("no error for a line past the buffer")
	}
}

func TestStepSkipsAnExpiredCache(t *testing.T) {
	// Resumed or woken 3h after the last request: the cache is gone, and a
	// heartbeat would only pay the rewrite early.
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("13:00:05"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("expired: pushes=%d, want 0", *pushes)
	}
	h.Now = func() time.Time { return at("10:59:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("due and still warm: pushes=%d, want 1", *pushes)
	}
}

func TestScanTranscript(t *testing.T) {
	tr := rec("user", "10:00:00", human) +
		rec("assistant", "10:00:05", reply) +
		rec("user", "10:00:06", toolRes) +
		rec("assistant", "10:00:10", reply) +
		rec("attachment", "10:00:11", "") +
		rec("user", "10:50:10", beat) +
		rec("user", "10:50:11", metaNote) + // a meta record that is not a channel stays in the turn
		rec("assistant", "10:50:12", reply) +
		rec("user", "10:50:13", toolRes) + // a tool result inside a heartbeat turn stays in it
		rec("assistant", "10:50:14", reply) +
		"not json\n"

	s := mustScan(t, tr)
	if !s.LastAssistant.Equal(at("10:50:14")) {
		t.Errorf("LastAssistant = %v, want the heartbeat's reply", s.LastAssistant)
	}
	if !s.LastReal.Equal(at("10:00:10")) {
		t.Errorf("LastReal = %v, want the last record before the heartbeat", s.LastReal)
	}
	if !s.LastBeat.Equal(at("10:50:10")) {
		t.Errorf("LastBeat = %v", s.LastBeat)
	}

	// Quoting the attribute is not a heartbeat: a person asking about it, a tool
	// reading this code, an attachment carrying the instructions.
	for _, quote := range []string{
		`,"message":{"role":"user","content":"what does kind=\"heartbeat\" mean?"}`,
		`,"message":{"role":"user","content":[{"type":"tool_result","content":"<channel source=\"ccx\" kind=\"heartbeat\">"}]}`,
		`,"message":{"role":"user","content":"<channel source=\"ccx\" kind=\"heartbeat\"> pasted by a person"}`,
		`,"isMeta":true,"message":{"role":"user","content":"<channel source=\"akapen\" file=\"a.md\">\nwhy kind=\"heartbeat\"?\n</channel>"}`,
		`,"isMeta":true,"message":{"role":"user","content":"<channel source=\"other\" event_kind=\"heartbeat\">\nhi\n</channel>"}`,
	} {
		s = mustScan(t, rec("user", "10:00:00", human)+rec("user", "10:10:00", quote)+rec("assistant", "10:10:05", reply))
		if !s.LastBeat.IsZero() || !s.LastReal.Equal(at("10:10:05")) {
			t.Errorf("%s: LastBeat=%v LastReal=%v, want no beat and real use", quote[:40], s.LastBeat, s.LastReal)
		}
	}
	s = mustScan(t, rec("attachment", "10:00:00", `,"attachment":{"content":"<channel source=\"ccx\" kind=\"heartbeat\">"}`))
	if !s.LastBeat.IsZero() {
		t.Errorf("attachment read as a beat")
	}

	// A person speaking again ends the heartbeat turn; so does another channel.
	for _, next := range []string{human, otherChan} {
		s = mustScan(t, tr+rec("user", "11:00:00", next)+rec("assistant", "11:00:02", reply))
		if !s.LastReal.Equal(at("11:00:02")) {
			t.Errorf("after %s: LastReal = %v, want 11:00:02", next[:30], s.LastReal)
		}
	}
}

// fixture writes a session transcript under a temp ClaudeHome and returns a
// Heartbeat whose clock and push are recorded.
func fixture(t *testing.T, transcript string, now time.Time) (*Heartbeat, *int, func(string)) {
	t.Helper()
	home := t.TempDir()
	dir := filepath.Join(home, "projects", "-some-cwd")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(dir, "sid.jsonl")
	pushes := 0
	h := &Heartbeat{
		SessionID: "sid", ClaudeHome: home, Interval: 50 * time.Minute, MaxIdle: 12 * time.Hour, Default: true,
		Push: func() error { pushes++; return nil },
		Log:  t.Logf,
		Now:  func() time.Time { return now },
	}
	write := func(s string) {
		if err := os.WriteFile(file, []byte(s), 0o644); err != nil {
			t.Fatal(err)
		}
		h.mtime = time.Time{} // same-second rewrites keep the mtime; force a rescan
	}
	write(transcript)
	return h, &pushes, write
}

func TestStepPushesOnlyWhenDue(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)

	h, pushes, _ := fixture(t, tr, at("10:30:05"))
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != 19*time.Minute+55*time.Second {
		t.Errorf("before due: pushes=%d wait=%v, want 0 and the time left", *pushes, wait)
	}

	h.Now = func() time.Time { return at("10:50:05") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("at due: pushes=%d, want 1", *pushes)
	}
}

func TestStepNeverStacksAnUndeliveredBeat(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, write := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)

	// Minutes later, cache still warm, still not in the transcript (/clear moved
	// the session on): no second push over the first.
	h.Now = func() time.Time { return at("10:55:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("undelivered: pushes=%d, want still 1", *pushes)
	}

	// Once it lands and is answered, the next one is due an interval after that
	// heartbeat's request started (10:50:06), not after the person's last turn.
	write(tr + rec("user", "10:50:06", beat) + rec("assistant", "10:50:08", reply))
	h.Now = func() time.Time { return at("11:30:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("before the next due: pushes=%d, want still 1", *pushes)
	}
	h.Now = func() time.Time { return at("11:40:06") }
	h.step(&sent)
	if *pushes != 2 {
		t.Fatalf("an interval after the heartbeat's request: pushes=%d, want 2", *pushes)
	}
}

// A request that started at 10:00 and answered at 10:12: the cache was read at
// 10:00, so the heartbeat is due at 10:50 and the cache is gone at 11:00. Counting
// from the answer would beat at 11:02, after it expired.
func TestStepCountsFromTheStartOfTheLastRequest(t *testing.T) {
	// An attachment sits between the prompt and the response, as in real transcripts.
	tr := rec("user", "10:00:00", human) + rec("attachment", "10:00:00", "") + rec("assistant", "10:12:00", reply)
	h, pushes, _ := fixture(t, tr, at("10:49:00"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("before request start + interval: pushes=%d, want 0", *pushes)
	}
	h.Now = func() time.Time { return at("10:50:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("at request start + interval: pushes=%d, want 1", *pushes)
	}

	// 11:05: past the hour from the request's start, before 11:02 + slack from the
	// answer, so only the request-start clock says expired.
	h2, pushes2, _ := fixture(t, tr, at("11:05:00"))
	var sent2 time.Time
	h2.step(&sent2)
	if *pushes2 != 0 {
		t.Errorf("an hour after the request started: pushes=%d, want 0 (expired)", *pushes2)
	}
}

// A turn is running when its input is newer than the last response: a person
// who came back just past the interval, a long tool call. A heartbeat then would
// only queue behind the turn. Input left without a response for longer than
// turnStart (a /model run, an Esc) is not a turn.
func TestStepWaitsForARunningTurn(t *testing.T) {
	base := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	cmd := `,"message":{"role":"user","content":"<command-name>/model</command-name>"}`
	out := `,"message":{"role":"user","content":"<local-command-stdout>Set model</local-command-stdout>"}`
	for _, c := range []struct {
		name string
		tr   string
		want int
	}{
		{"a person's prompt with no answer yet", base + rec("user", "10:50:03", human), 0},
		{"a tool result with no answer yet", base + rec("user", "10:50:03", toolRes), 0},
		{"a tool still running", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", toolUse), 0},
		{"a tool that finished and was answered", rec("user", "10:00:00", human) + rec("assistant", "10:00:01", toolUse) + rec("user", "10:00:02", toolRes) + rec("assistant", "10:00:05", reply), 1},
		{"a /model run and left", base + rec("user", "10:40:00", cmd) + rec("user", "10:40:00", out), 1},
		{"an interrupt (Esc) 6 minutes ago, never answered", base + rec("user", "10:44:00", interrupted), 1},
		{"a /model run a minute before due", base + rec("user", "10:49:05", cmd) + rec("user", "10:49:05", out), 1},
		{"a tool running while another record lands", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", toolUse) + rec("user", "10:20:00", crossMsg), 0},
		{"a tool interrupted by Esc", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", toolUse) + rec("user", "10:10:00", interrupted), 1},
		{"one of two parallel tools returned", rec("user", "10:00:00", human) + rec("assistant", "10:00:04", toolUse) + rec("assistant", "10:00:05", toolUse2) + rec("user", "10:00:06", toolRes), 0},
		{"a text record after the tool call", rec("user", "10:00:00", human) + rec("assistant", "10:00:04", toolUse) + rec("assistant", "10:00:05", reply), 0},
		{"the second of two parallel tools returned first", rec("user", "10:00:00", human) + rec("assistant", "10:00:04", toolUse) + rec("assistant", "10:00:05", toolUse2) + rec("user", "10:00:06", toolRes2), 0},
		{"a result for a tool nobody called", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", toolUse) + rec("user", "10:00:06", toolResX), 0},
		{"both parallel tools returned and were answered", rec("user", "10:00:00", human) + rec("assistant", "10:00:01", toolUse) + rec("assistant", "10:00:01", toolUse2) + rec("user", "10:00:02", toolRes) + rec("user", "10:00:02", toolRes2) + rec("assistant", "10:00:05", reply), 1},
	} {
		h, pushes, _ := fixture(t, c.tr, at("10:50:05"))
		var sent time.Time
		h.step(&sent)
		if *pushes != c.want {
			t.Errorf("%s: pushes=%d, want %d", c.name, *pushes, c.want)
		}
	}
}

func TestStepRecoversFromALostBeat(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, write := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)

	// The push was lost (interrupted, dropped), but the person came back and used
	// the session. That session is alive; it must be kept warm again.
	tr += rec("user", "11:00:00", human) + rec("assistant", "11:00:05", reply)
	write(tr)
	h.Now = func() time.Time { return at("11:50:05") }
	h.step(&sent)
	if *pushes != 2 {
		t.Fatalf("after real use: pushes=%d, want 2", *pushes)
	}
}

func TestStepDoesNotRepeatAnUnansweredBeat(t *testing.T) {
	// Delivered, but the answer never came (the request failed).
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) + rec("user", "10:50:06", beat)
	h, pushes, _ := fixture(t, tr, at("10:51:06"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Fatalf("a minute after an unanswered beat: pushes=%d, want 0", *pushes)
	}
	// An interval after it the cache is gone: the last request that answered was
	// 10:00:00. The failed heartbeat read nothing, so it does not keep it alive.
	// Past turnStart it no longer looks like a running turn, and it is still not
	// sent again: the next is due an interval after the unanswered one.
	h.Now = func() time.Time { return at("10:56:06") }
	h.step(&sent)
	if *pushes != 0 {
		t.Fatalf("6 minutes after an unanswered beat, cache warm: pushes=%d, want 0", *pushes)
	}
	// step says wait an interval rather than a poll, as for a running turn (Run
	// still wakes every poll, so a declaration change is seen within a minute).
	h.Now = func() time.Time { return at("11:40:06") }
	if wait := h.step(&sent); *pushes != 0 || wait != h.Interval {
		t.Fatalf("after a failed beat, past the TTL: pushes=%d wait=%v, want 0 and %v", *pushes, wait, h.Interval)
	}
}

func TestStepStopsWhenLeftAlone(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "21:50:00", beat) + rec("assistant", "21:50:02", reply)
	// The last heartbeat was answered; 12h after the person last used it, stop.
	h, pushes, _ := fixture(t, tr, at("22:40:02"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("past MaxIdle: pushes=%d, want 0", *pushes)
	}
	h.MaxIdle = 24 * time.Hour
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("within MaxIdle: pushes=%d, want 1", *pushes)
	}

	// off (0) is no cap, not "always past it".
	h2, pushes2, _ := fixture(t, tr, at("22:40:02"))
	h2.MaxIdle = 0
	var sent2 time.Time
	h2.step(&sent2)
	if *pushes2 != 1 {
		t.Errorf("MaxIdle off: pushes=%d, want 1", *pushes2)
	}
}

// A session's own on / off wins over the machine's default, both ways, and a
// change takes effect on the next step without a restart.
func TestStepFollowsTheSessionsDeclaration(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	for _, c := range []struct {
		def  bool
		file string
		want int
	}{
		{true, "", 1}, {false, "", 0},
		{true, "off\n", 0}, {false, "on\n", 1},
		{false, "garbage", 0}, {true, "garbage", 1},
	} {
		h, pushes, _ := fixture(t, tr, at("10:50:05"))
		h.Default = c.def
		if c.file != "" {
			dir := filepath.Join(h.ClaudeHome, "sessions", "sid")
			_ = os.MkdirAll(dir, 0o755)
			_ = os.WriteFile(filepath.Join(dir, "heartbeat"), []byte(c.file), 0o644)
		}
		var sent time.Time
		if wait := h.step(&sent); *pushes != c.want {
			t.Errorf("default=%v file=%q: pushes=%d, want %d", c.def, c.file, *pushes, c.want)
		} else if c.want == 0 && wait != poll {
			t.Errorf("default=%v file=%q: wait=%v, want poll so turning it on is seen soon", c.def, c.file, wait)
		}
	}
}

// The same running Heartbeat follows a declaration made while it runs, both ways:
// nothing about the declaration is cached between steps.
func TestStepFollowsADeclarationChangedWhileRunning(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:05"))
	h.Default = false
	file := filepath.Join(h.ClaudeHome, "sessions", "sid", "heartbeat")
	_ = os.MkdirAll(filepath.Dir(file), 0o755)
	var sent time.Time

	h.step(&sent)
	_ = os.WriteFile(file, []byte("on\n"), 0o644)
	h.step(&sent)
	if *pushes != 1 {
		t.Fatalf("after declaring on: pushes=%d, want 1", *pushes)
	}

	// Delivered and answered; later, declared off before the next is due.
	h.Default = true
	tr += rec("user", "10:50:06", beat) + rec("assistant", "10:50:08", reply)
	_ = os.WriteFile(filepath.Join(h.ClaudeHome, "projects", "-some-cwd", "sid.jsonl"), []byte(tr), 0o644)
	h.mtime = time.Time{}
	_ = os.WriteFile(file, []byte("off\n"), 0o644)
	h.Now = func() time.Time { return at("11:40:06") }
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("after declaring off, with the default on: pushes=%d, want still 1", *pushes)
	}
}

func TestStepSkipsArchived(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:05"))
	dir := filepath.Join(h.ClaudeHome, "sessions", "sid")
	_ = os.MkdirAll(dir, 0o755)
	_ = os.WriteFile(filepath.Join(dir, "archived"), nil, 0o644)
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("archived: pushes=%d, want 0", *pushes)
	}
}

func TestStepWaitsForATranscript(t *testing.T) {
	h, pushes, _ := fixture(t, "", at("10:50:05"))
	h.SessionID = "not-started"
	var sent time.Time
	if wait := h.step(&sent); *pushes != 0 || wait != poll {
		t.Errorf("no transcript: pushes=%d wait=%v", *pushes, wait)
	}
}

// Run never sleeps past a poll, even with the next heartbeat 20 minutes away:
// a declaration made in between must be seen within a minute.
func TestRunSleepsAtMostAPoll(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply)
	h, _, _ := fixture(t, tr, at("10:30:05"))
	ctx, cancel := context.WithCancel(context.Background())
	var slept time.Duration
	h.Sleep = func(_ context.Context, d time.Duration) { slept = d; cancel() }
	h.Run(ctx)
	if slept != poll {
		t.Errorf("slept %v, want %v", slept, poll)
	}
}

// A session whose cache is written for 5 minutes (API key, usage credits) is
// never beaten: 50 minutes later it is always gone. A request that wrote no
// cache does not change what is known.
func TestStepSkipsAFiveMinuteCache(t *testing.T) {
	usage := func(short, long int) string {
		return fmt.Sprintf(`,"message":{"role":"assistant","content":[],"usage":{"cache_creation":{"ephemeral_5m_input_tokens":%d,"ephemeral_1h_input_tokens":%d}}}`, short, long)
	}
	for _, c := range []struct {
		name string
		tr   string
		want int
	}{
		{"5m", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", usage(180000, 0)), 0},
		{"1h", rec("user", "10:00:00", human) + rec("assistant", "10:00:05", usage(0, 180000)), 1},
		{"5m, then a request writing nothing", rec("user", "10:00:00", human) + rec("assistant", "10:00:01", usage(180000, 0)) + rec("assistant", "10:00:05", usage(0, 0)), 0},
	} {
		h, pushes, _ := fixture(t, c.tr, at("10:50:05"))
		var sent time.Time
		h.step(&sent)
		if *pushes != c.want {
			t.Errorf("%s: pushes=%d, want %d", c.name, *pushes, c.want)
		}
	}
}

// A meta record that starts a turn (a cross-session message) is that turn's
// request start: the response is traced up its parentUuid chain, not matched on
// what the record says.
func TestStepCountsFromAMetaRecordThatStartedTheTurn(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "10:30:00", crossMsg) + rec("attachment", "10:30:00", "") + rec("assistant", "10:30:04", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:05"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("50m after the old prompt, 20m after the message's turn: pushes=%d, want 0", *pushes)
	}
	h.Now = func() time.Time { return at("11:20:00") }
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("50m after the message's turn: pushes=%d, want 1", *pushes)
	}
}

// A synthetic API-error reply ("Prompt is too long") read no cache, so it is not
// an answer: the cache counts from the last real one and expires on time, and a
// session stuck failing is not woken every 50 minutes.
func TestStepIgnoresAPIErrorReplies(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", reply) +
		rec("user", "10:40:00", human) + rec("assistant", "10:40:01", apiError)
	// 11:30:02: counted from the error reply (10:40:01) this would be due.
	h, pushes, _ := fixture(t, tr, at("11:30:02"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 0 {
		t.Errorf("50m after the failed request, 90m after the last answer: pushes=%d, want 0", *pushes)
	}
}

// One response is often several assistant records (thinking, then text). A later
// record's parent is the earlier one; it answers the same request.
func TestStepTracesAResponseSplitAcrossRecords(t *testing.T) {
	thinking := `,"message":{"role":"assistant","content":[{"type":"thinking","thinking":"..."}]}`
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:30", thinking) + rec("assistant", "10:12:00", reply)
	h, pushes, _ := fixture(t, tr, at("10:50:00"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("50m after the prompt the split response answered: pushes=%d, want 1", *pushes)
	}
}

// The response's parentUuid decides which input it answers, not which user
// record came last: a later record that is not its parent (a sibling, a record
// written out of order) does not move the request start.
func TestStepFollowsTheParentNotTheLatestInput(t *testing.T) {
	tr := `{"type":"user","uuid":"p1","timestamp":"2026-09-23T10:00:00.000Z"` + human + "}\n" +
		`{"type":"user","uuid":"p2","timestamp":"2026-09-23T10:20:00.000Z"` + crossMsg + "}\n" +
		`{"type":"assistant","uuid":"a1","parentUuid":"p1","timestamp":"2026-09-23T10:20:05.000Z"` + reply + "}\n"
	h, pushes, _ := fixture(t, tr, at("10:50:00"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("50m after the parent prompt: pushes=%d, want 1", *pushes)
	}
}

// A tool call left without a result (a rewind, a crash) does not stop keepalive
// for good: once a later request is answered, it is dropped.
func TestStepDropsAnAbandonedToolCall(t *testing.T) {
	tr := rec("user", "10:00:00", human) + rec("assistant", "10:00:05", toolUse) +
		rec("user", "10:20:00", human) + rec("assistant", "10:20:05", reply)
	h, pushes, _ := fixture(t, tr, at("11:10:00"))
	var sent time.Time
	h.step(&sent)
	if *pushes != 1 {
		t.Errorf("50m after a later answered prompt: pushes=%d, want 1", *pushes)
	}
}
